services:
  smile-service:
    build: ./models/smile-service
    expose:
      - "8000"

  glasses-service:
    build: ./models/glasses-service
    expose:
      - "8000"

  eyes-service:
    build: ./models/eyes-service
    expose:
      - "8000"

  gateway:
    build: ./gateway
    environment:
      SMILE_SERVICE_URL: http://smile-service:8000
      GLASSES_SERVICE_URL: http://glasses-service:8000
      EYES_SERVICE_URL: http://eyes-service:8000
    depends_on:
      - smile-service
      - glasses-service
      - eyes-service
    expose:
      - "8000"

  frontend:
    build: ./frontend
    environment:
      GATEWAY_URL: http://gateway:8000
    depends_on:
      - gateway
    ports:
      - "5000:5000"
